//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praetorium.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Praetorium.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; parameter is equal to the default value of the type..
        /// </summary>
        internal static string ArgumentDefaultExceptionMessage {
            get {
                return ResourceManager.GetString("ArgumentDefaultExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; parameter may not be null..
        /// </summary>
        internal static string ArgumentNullExceptionMessage {
            get {
                return ResourceManager.GetString("ArgumentNullExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; parameter may not be null or empty..
        /// </summary>
        internal static string ArgumentNullOrDefaultExceptionMessage {
            get {
                return ResourceManager.GetString("ArgumentNullOrDefaultExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; parameter may not be null or empty..
        /// </summary>
        internal static string ArgumentNullOrEmptyExceptionMessage {
            get {
                return ResourceManager.GetString("ArgumentNullOrEmptyExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Channel factories were released and disposed..
        /// </summary>
        internal static string ChannelFactoriesDisposed {
            get {
                return ResourceManager.GetString("ChannelFactoriesDisposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was unable to create a ChannelFactory for the ServiceContract &apos;{0}&apos;.  This is typically due to an invalid endpoint configuration name.  The endpoint name used was &apos;{1}&apos;.  Please check the inner exception for more details..
        /// </summary>
        internal static string ChannelFactoryCreateFailed {
            get {
                return ResourceManager.GetString("ChannelFactoryCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ServiceContract &apos;{0}&apos; is not marked with the DefaultEnpointName attribute, and cannot be associated to an endpoint configuration.  Please use a GetProxy() overload that specifies connection information including binding and endpoint address, or use the DefaultEndpointNameAttribute on the service contract interface to specify the name of the endpoint configuration..
        /// </summary>
        internal static string ChannelFactoryWithNoEndpoint {
            get {
                return ResourceManager.GetString("ChannelFactoryWithNoEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} setting is missing or invalid..
        /// </summary>
        internal static string ConfigurationSettingMissingOrInvalid {
            get {
                return ResourceManager.GetString("ConfigurationSettingMissingOrInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DataSource with a name of &apos;{0}&apos; does not exist, or is improperly configured.  Please ensure that you have a connectionString setting with a name equal to &apos;{0}&apos;, and that it is properly configured..
        /// </summary>
        internal static string DataSourceMissingOrInvalid {
            get {
                return ResourceManager.GetString("DataSourceMissingOrInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The exception formatter configuration is invalid for the following reasons: {0}.
        /// </summary>
        internal static string ExceptionFormatterConfigurationError {
            get {
                return ResourceManager.GetString("ExceptionFormatterConfigurationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of the argument &apos;{0}&apos; provided for the enumeration &apos;{1}&apos; is invalid..
        /// </summary>
        internal static string InvalidEnumValueExceptionMessage {
            get {
                return ResourceManager.GetString("InvalidEnumValueExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is an invalid value for &apos;{1}&apos;..
        /// </summary>
        internal static string InvalidValueExceptionMessage {
            get {
                return ResourceManager.GetString("InvalidValueExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listener &apos;{0}&apos; registered..
        /// </summary>
        internal static string ListenerRegistered {
            get {
                return ResourceManager.GetString("ListenerRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} event subscription for target &apos;{1}&apos; threw an unhandled exception..
        /// </summary>
        internal static string ListenerSubscriptionThrewException {
            get {
                return ResourceManager.GetString("ListenerSubscriptionThrewException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no current instance of HttpContext..
        /// </summary>
        internal static string NoCurrentHttpContext {
            get {
                return ResourceManager.GetString("NoCurrentHttpContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no current WCF operation context..
        /// </summary>
        internal static string NoCurrentOperationContext {
            get {
                return ResourceManager.GetString("NoCurrentOperationContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lambda or delegate expression used produces a Target that is compiler generated.  This type of delegate is not supported by the Event Aggregator due to reference tracking issues..
        /// </summary>
        internal static string NoNonStaticCompilerGeneratedClassesAllowed {
            get {
                return ResourceManager.GetString("NoNonStaticCompilerGeneratedClassesAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided type is not an enum type..
        /// </summary>
        internal static string NotAnEnumTypeExceptionMessage {
            get {
                return ResourceManager.GetString("NotAnEnumTypeExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reader is closed..
        /// </summary>
        internal static string ReaderClosed {
            get {
                return ResourceManager.GetString("ReaderClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The return value of method &apos;{0}&apos; is null..
        /// </summary>
        internal static string ReturnValueIsNullExceptionMessage {
            get {
                return ResourceManager.GetString("ReturnValueIsNullExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The return value of method &apos;{0}&apos; is null or empty..
        /// </summary>
        internal static string ReturnValueIsNullOrEmptyExceptionMessage {
            get {
                return ResourceManager.GetString("ReturnValueIsNullOrEmptyExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The return value of method &apos;{0}&apos; is the default value..
        /// </summary>
        internal static string ReturnValueIsTheDefaultExceptionMessage {
            get {
                return ResourceManager.GetString("ReturnValueIsTheDefaultExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ServiceLocationProperties.ServiceConfigurationName property is required, and must specify a name of an endpoint configuration..
        /// </summary>
        internal static string ServiceConfigurationNameRequired {
            get {
                return ResourceManager.GetString("ServiceConfigurationNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected exception has occurred in the ServiceTypeCache for the ServiceContract &apos;{0&apos;}.  Please see the InnerException for more details..
        /// </summary>
        internal static string ServiceTypeCacheUnexpectedException {
            get {
                return ResourceManager.GetString("ServiceTypeCacheUnexpectedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TSection does not define the DefaultSectionNameAttribute.  Either specify this attribute, or use the GetSection overload with the sectionName parameter..
        /// </summary>
        internal static string TypeDoesNotSpecifySectionName {
            get {
                return ResourceManager.GetString("TypeDoesNotSpecifySectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a service contract and a ChannelFactory could not be created for this type..
        /// </summary>
        internal static string TypeNotServiceContract {
            get {
                return ResourceManager.GetString("TypeNotServiceContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; parameter must be the same type as, or inherit from, &apos;{1}&apos;..
        /// </summary>
        internal static string TypeNotSupportedExceptionMessage {
            get {
                return ResourceManager.GetString("TypeNotSupportedExceptionMessage", resourceCulture);
            }
        }
    }
}
